name: Deploy pipeline


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
            host: 54.205.23.211
            username: ubuntu
            key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
            script: |
                cd hng12-stage2-cicd
                git stash
                git pull origin main
                source venv/bin/activate
                pip install -r requirements.txt
                sudo systemctl restart fastapi
