name: Deploy pipeline

on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secret.EC2_HOST }} << 'EOF'
            set -e

            APP_DIR="/home/ubuntu/app"

            if [ ! -d "$APP_DIR/.git" ]; then
              git clone https://github.com/george-eki/hng12-stage2-cicd.git $APP_DIR
            fi
            cd $APP_DIR
            git pull origin main

            docker stop fastapi-app || true
            docker rm fastapi-app || true

            docker build -t fastapi-app .
            docker run -d -p 8000:8000 --name fastapi-app fastapi-app

            sudo systemctl restart nginx
          EOF
